worldnews_project:
  outputs:
    dev:
      dataset: reddit_data
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: argon-tuner-410118
      threads: 2
      type: bigquery
  target: dev