{{ config(materialized='table') }}

WITH tokenized_titles AS (
    SELECT
        id,
        title,
        LOWER(title) AS lower_title,
        CASE
            WHEN LOWER(title) LIKE '%china%' THEN 'China'
            WHEN LOWER(title) LIKE '%india%' THEN 'India'
            WHEN LOWER(title) LIKE '%united states%' OR LOWER(title) LIKE '%usa%' OR LOWER(title) LIKE '%america%' THEN 'United States'
            WHEN LOWER(title) LIKE '%indonesia%' THEN 'Indonesia'
            WHEN LOWER(title) LIKE '%pakistan%' THEN 'Pakistan'
            WHEN LOWER(title) LIKE '%brazil%' THEN 'Brazil'
            WHEN LOWER(title) LIKE '%nigeria%' THEN 'Nigeria'
            WHEN LOWER(title) LIKE '%bangladesh%' THEN 'Bangladesh'
            WHEN LOWER(title) LIKE '%russia%' THEN 'Russia'
            WHEN LOWER(title) LIKE '%mexico%' THEN 'Mexico'
            WHEN LOWER(title) LIKE '%japan%' THEN 'Japan'
            WHEN LOWER(title) LIKE '%ethiopia%' THEN 'Ethiopia'
            WHEN LOWER(title) LIKE '%philippines%' THEN 'Philippines'
            WHEN LOWER(title) LIKE '%egypt%' THEN 'Egypt'
            WHEN LOWER(title) LIKE '%vietnam%' THEN 'Vietnam'
            WHEN LOWER(title) LIKE '%dr congo%' OR LOWER(title) LIKE '%democratic republic of the congo%' THEN 'DR Congo'
            WHEN LOWER(title) LIKE '%turkey%' THEN 'Turkey'
            WHEN LOWER(title) LIKE '%iran%' THEN 'Iran'
            WHEN LOWER(title) LIKE '%germany%' THEN 'Germany'
            WHEN LOWER(title) LIKE '%thailand%' THEN 'Thailand'
            WHEN LOWER(title) LIKE '%united kingdom%' OR LOWER(title) LIKE '%uk%' OR LOWER(title) LIKE '%britain%' THEN 'United Kingdom'
            WHEN LOWER(title) LIKE '%france%' THEN 'France'
            WHEN LOWER(title) LIKE '%italy%' THEN 'Italy'
            WHEN LOWER(title) LIKE '%tanzania%' THEN 'Tanzania'
            WHEN LOWER(title) LIKE '%south africa%' THEN 'South Africa'
            WHEN LOWER(title) LIKE '%myanmar%' THEN 'Myanmar'
            WHEN LOWER(title) LIKE '%kenya%' THEN 'Kenya'
            WHEN LOWER(title) LIKE '%south korea%' THEN 'South Korea'
            WHEN LOWER(title) LIKE '%colombia%' THEN 'Colombia'
            WHEN LOWER(title) LIKE '%spain%' THEN 'Spain'
            WHEN LOWER(title) LIKE '%uganda%' THEN 'Uganda'
            WHEN LOWER(title) LIKE '%argentina%' THEN 'Argentina'
            WHEN LOWER(title) LIKE '%algeria%' THEN 'Algeria'
            WHEN LOWER(title) LIKE '%sudan%' THEN 'Sudan'
            WHEN LOWER(title) LIKE '%ukraine%' THEN 'Ukraine'
            WHEN LOWER(title) LIKE '%iraq%' THEN 'Iraq'
            WHEN LOWER(title) LIKE '%afghanistan%' THEN 'Afghanistan'
            WHEN LOWER(title) LIKE '%poland%' THEN 'Poland'
            WHEN LOWER(title) LIKE '%canada%' THEN 'Canada'
            WHEN LOWER(title) LIKE '%morocco%' THEN 'Morocco'
            WHEN LOWER(title) LIKE '%saudi arabia%' THEN 'Saudi Arabia'
            WHEN LOWER(title) LIKE '%uzbekistan%' THEN 'Uzbekistan'
            WHEN LOWER(title) LIKE '%peru%' THEN 'Peru'
            WHEN LOWER(title) LIKE '%angola%' THEN 'Angola'
            WHEN LOWER(title) LIKE '%malaysia%' THEN 'Malaysia'
            WHEN LOWER(title) LIKE '%mozambique%' THEN 'Mozambique'
            WHEN LOWER(title) LIKE '%yemen%' THEN 'Yemen'
            WHEN LOWER(title) LIKE '%ghana%' THEN 'Ghana'
            WHEN LOWER(title) LIKE '%nepal%' THEN 'Nepal'
            WHEN LOWER(title) LIKE '%venezuela%' THEN 'Venezuela'
            WHEN LOWER(title) LIKE '%madagascar%' THEN 'Madagascar'
            WHEN LOWER(title) LIKE '%cameroon%' THEN 'Cameroon'
            WHEN LOWER(title) LIKE '%north korea%' THEN 'North Korea'
            WHEN LOWER(title) LIKE '%australia%' THEN 'Australia'
            WHEN LOWER(title) LIKE '%niger%' THEN 'Niger'
            WHEN LOWER(title) LIKE '%sri lanka%' THEN 'Sri Lanka'
            WHEN LOWER(title) LIKE '%burkina faso%' THEN 'Burkina Faso'
            WHEN LOWER(title) LIKE '%mali%' THEN 'Mali'
            WHEN LOWER(title) LIKE '%chile%' THEN 'Chile'
            WHEN LOWER(title) LIKE '%romania%' THEN 'Romania'
            WHEN LOWER(title) LIKE '%kazakhstan%' THEN 'Kazakhstan'
            WHEN LOWER(title) LIKE '%malawi%' THEN 'Malawi'
            WHEN LOWER(title) LIKE '%zambia%' THEN 'Zambia'
            WHEN LOWER(title) LIKE '%senegal%' THEN 'Senegal'
            WHEN LOWER(title) LIKE '%guatemala%' THEN 'Guatemala'
            WHEN LOWER(title) LIKE '%ecuador%' THEN 'Ecuador'
            WHEN LOWER(title) LIKE '%syria%' THEN 'Syria'
            WHEN LOWER(title) LIKE '%netherlands%' THEN 'Netherlands'
            WHEN LOWER(title) LIKE '%cambodia%' THEN 'Cambodia'
            WHEN LOWER(title) LIKE '%chad%' THEN 'Chad'
            WHEN LOWER(title) LIKE '%somalia%' THEN 'Somalia'
            WHEN LOWER(title) LIKE '%zimbabwe%' THEN 'Zimbabwe'
            WHEN LOWER(title) LIKE '%guinea%' THEN 'Guinea'
            WHEN LOWER(title) LIKE '%south sudan%' THEN 'South Sudan'
            WHEN LOWER(title) LIKE '%rwanda%' THEN 'Rwanda'
            WHEN LOWER(title) LIKE '%benin%' THEN 'Benin'
            WHEN LOWER(title) LIKE '%burundi%' THEN 'Burundi'
            WHEN LOWER(title) LIKE '%tunisia%' THEN 'Tunisia'
            WHEN LOWER(title) LIKE '%bolivia%' THEN 'Bolivia'
            WHEN LOWER(title) LIKE '%belgium%' THEN 'Belgium'
            WHEN LOWER(title) LIKE '%haiti%' THEN 'Haiti'
            WHEN LOWER(title) LIKE '%cuba%' THEN 'Cuba'
            WHEN LOWER(title) LIKE '%south sudan%' THEN 'South Sudan'
            WHEN LOWER(title) LIKE '%dominican republic%' THEN 'Dominican Republic'
            WHEN LOWER(title) LIKE '%czech republic%' THEN 'Czech Republic'
            WHEN LOWER(title) LIKE '%greece%' THEN 'Greece'
            WHEN LOWER(title) LIKE '%jordan%' THEN 'Jordan'
            WHEN LOWER(title) LIKE '%portugal%' THEN 'Portugal'
            WHEN LOWER(title) LIKE '%azerbaijan%' THEN 'Azerbaijan'
            WHEN LOWER(title) LIKE '%sweden%' THEN 'Sweden'
            WHEN LOWER(title) LIKE '%honduras%' THEN 'Honduras'
            WHEN LOWER(title) LIKE '%united arab emirates%' OR LOWER(title) LIKE '%uae%' THEN 'United Arab Emirates'
            WHEN LOWER(title) LIKE '%hungary%' THEN 'Hungary'
            WHEN LOWER(title) LIKE '%tajikistan%' THEN 'Tajikistan'
            WHEN LOWER(title) LIKE '%belarus%' THEN 'Belarus'
            WHEN LOWER(title) LIKE '%austria%' THEN 'Austria'
            WHEN LOWER(title) LIKE '%papua new guinea%' THEN 'Papua New Guinea'
            WHEN LOWER(title) LIKE '%serbia%' THEN 'Serbia'
            WHEN LOWER(title) LIKE '%israel%' THEN 'Israel'
            WHEN LOWER(title) LIKE '%switzerland%' THEN 'Switzerland'
            WHEN LOWER(title) LIKE '%togo%' THEN 'Togo'
            WHEN LOWER(title) LIKE '%sierra leone%' THEN 'Sierra Leone'
            WHEN LOWER(title) LIKE '%laos%' THEN 'Laos'
            WHEN LOWER(title) LIKE '%gaza%' THEN 'Gaza'
            WHEN LOWER(title) LIKE '%ukraine%' THEN 'Ukraine'
            ELSE NULL
        END AS country
    FROM {{ ref('stg_reddit_worldnews') }}
)



SELECT 
    country,
    title,
    COUNT(*) as freq
FROM tokenized_titles
GROUP BY country, title
ORDER BY country, title